package db.entity;
// Generated 22-May-2016 08:20:38 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Accident generated by hbm2java
 */
@Entity
@Table(name="accident"
    ,catalog="my_db"
)
public class Accident  implements java.io.Serializable {


     private int accId;
     private String accLoc;
     private Double accLat;
     private Double accLong;
     private Info info;

    public Accident() {
    }

	
    public Accident(int accId) {
        this.accId = accId;
    }
    public Accident(int accId, String accLoc, Double accLat, Double accLong, Info info) {
       this.accId = accId;
       this.accLoc = accLoc;
       this.accLat = accLat;
       this.accLong = accLong;
       this.info = info;
    }
   
     @Id 

    
    @Column(name="acc_id", unique=true, nullable=false)
    public int getAccId() {
        return this.accId;
    }
    
    public void setAccId(int accId) {
        this.accId = accId;
    }

    
    @Column(name="acc_loc", length=100)
    public String getAccLoc() {
        return this.accLoc;
    }
    
    public void setAccLoc(String accLoc) {
        this.accLoc = accLoc;
    }

    
    @Column(name="acc_lat", precision=22, scale=0)
    public Double getAccLat() {
        return this.accLat;
    }
    
    public void setAccLat(Double accLat) {
        this.accLat = accLat;
    }

    
    @Column(name="acc_long", precision=22, scale=0)
    public Double getAccLong() {
        return this.accLong;
    }
    
    public void setAccLong(Double accLong) {
        this.accLong = accLong;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="accident")
    public Info getInfo() {
        return this.info;
    }
    
    public void setInfo(Info info) {
        this.info = info;
    }




}


