package db.entity;
// Generated 22-May-2016 08:20:38 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Info generated by hbm2java
 */
@Entity
@Table(name="info"
    ,catalog="my_db"
)
public class Info  implements java.io.Serializable {


     private int accId;
     private Accident accident;
     private Post post;
     private int infoId;
     private Double distance;
     private Double time;

    public Info() {
    }

	
    public Info(Accident accident, Post post, int infoId) {
        this.accident = accident;
        this.post = post;
        this.infoId = infoId;
    }
    public Info(Accident accident, Post post, int infoId, Double distance, Double time) {
       this.accident = accident;
       this.post = post;
       this.infoId = infoId;
       this.distance = distance;
       this.time = time;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="accident"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="acc_id", unique=true, nullable=false)
    public int getAccId() {
        return this.accId;
    }
    
    public void setAccId(int accId) {
        this.accId = accId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Accident getAccident() {
        return this.accident;
    }
    
    public void setAccident(Accident accident) {
        this.accident = accident;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="post_id", nullable=false)
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }

    
    @Column(name="info_id", nullable=false)
    public int getInfoId() {
        return this.infoId;
    }
    
    public void setInfoId(int infoId) {
        this.infoId = infoId;
    }

    
    @Column(name="distance", precision=22, scale=0)
    public Double getDistance() {
        return this.distance;
    }
    
    public void setDistance(Double distance) {
        this.distance = distance;
    }

    
    @Column(name="time", precision=22, scale=0)
    public Double getTime() {
        return this.time;
    }
    
    public void setTime(Double time) {
        this.time = time;
    }




}


