package db.entity;
// Generated 22-May-2016 08:20:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name="post"
    ,catalog="my_db"
)
public class Post  implements java.io.Serializable {


     private int post_id;
     private String post_name;
     private Double post_lat;
     private Double post_long;
     private Set<Info> infos = new HashSet<Info>(0);

    public Post() {
    }

	
    public Post(int postId) {
        this.post_id = postId;
    }
    public Post(int postId, String postName, Double postLat, Double postLong, Set infos) {
       this.post_id = postId;
       this.post_name = postName;
       this.post_lat = postLat;
       this.post_long = postLong;
       this.infos = infos;
    }
   
     @Id 

    
    @Column(name="post_id", unique=true, nullable=false)
    public int getPost_id() {
        return this.post_id;
    }
    
    public void setPost_id(int post_id) {
        this.post_id = post_id;
    }

    
    @Column(name="post_name", length=100)
    public String getPost_name() {
        return this.post_name;
    }
    
    public void setPost_name(String post_name) {
        this.post_name = post_name;
    }

    
    @Column(name="post_lat", precision=22, scale=0)
    public Double getPost_lat() {
        return this.post_lat;
    }
    
    public void setPost_lat(Double post_lat) {
        this.post_lat = post_lat;
    }

    
    @Column(name="post_long", precision=22, scale=0)
    public Double getPost_long() {
        return this.post_long;
    }
    
    public void setPost_long(Double post_long) {
        this.post_long = post_long;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="post")
    public Set<Info> getInfos() {
        return this.infos;
    }
    
    public void setInfos(Set<Info> infos) {
        this.infos = infos;
    }




}


